###
POST http://localhost:3000/api/user/register HTTP/1:1
Content-Type: application/json

{
	"email": "mail@mail.com",
	"password": "password"
}
###
POST http://localhost:3000/api/user/login HTTP/1:1
Content-Type: application/json

{
	"email": "judegiordano@mail.com",
	"password": "Test1234!"
}

###
POST http://localhost:3000/api/user/validate HTTP/1:1
content-type: application/json
Authorization: Bearer token

###
POST http://localhost:3000/api/user/delete HTTP/1:1
content-type: application/json
Authorization: Bearer token

{
	"email": "mail@mail.com",
	"password": "password"
}

###
POST http://localhost:3000/api/user/update/email HTTP/1:1
content-type: application/json
Authorization: Bearer token

{
	"newEmail": "mail3@mail.com"
}

###
GET http://localhost:3000/api/utility/filter/user
?email=mail@mail.com
content-type: application/json
apptoken: {{$dotenv DEV_APPTOKEN}}
appcode: {{$dotenv DEV_APPCODE}}

###
POST http://localhost:3000/api/user/forgotpassword
content-type: application/json

{
	"email": "mail@mail.com"
}
